version: '3'

services:
    h-api-editor:
        build:
            context: .
            dockerfile: cmd/api-editor/Dockerfile
        ports:
            - 4242:4242
        restart: always
        links:
            - postgres:postgres
            - cassandra:cassandra
        environment:
            - HEROESBOOK_EDITOR_SSL_ENABLE=false
            - HEROESBOOK_EDITOR_SSL_CERT=resources/cert.pem
            - HEROESBOOK_EDITOR_SSL_KEY=resources/key.pem
            - HEROESBOOK_EDITOR_PORT=4242
            - HEROESBOOK_EDITOR_AUTH_ENABLE=true
            - HEROESBOOK_EDITOR_AUTH_JWT_KEY=--key-jwt--
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_USER=postgres
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_PASSWORD=pass_example
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_DB_NAME=heroes
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_SSL=disable
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_HOST=postgres
            - HEROESBOOK_EDITOR_AUTH_POSTGRES_PORT=5432
            - HEROESBOOK_EDITOR_AUTH_CASSANDRA_HOSTS=cassandra
            - HEROESBOOK_EDITOR_AUTH_CASSANDRA_KEYSPACE=heroesbook
            - HEROESBOOK_EDITOR_AUTH_CASSANDRA_PORT=9042
            - HEROESBOOK_EDITOR_APP_POSTGRES_USER=postgres
            - HEROESBOOK_EDITOR_APP_POSTGRES_PASSWORD=pass_example
            - HEROESBOOK_EDITOR_APP_POSTGRES_DB_NAME=heroes
            - HEROESBOOK_EDITOR_APP_POSTGRES_SSL=disable
            - HEROESBOOK_EDITOR_APP_POSTGRES_HOST=postgres
            - HEROESBOOK_EDITOR_APP_POSTGRES_PORT=5432

    h-view-editor:
        build:
            context: view/editor
            dockerfile: Dockerfile
            args:
                - API_HOST_ARG=http://127.0.0.1
                - API_PORT_ARG=4242
        ports:
            - 8080:8080
        links:
            - h-api-editor:h-api-editor

    postgres:
        image: postgres:12.0
        restart: always
        environment:
            - POSTGRES_DB=heroes
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pass_example
        volumes:
            - "./resources/psql/:/docker-entrypoint-initdb.d/"
        ports:
            - 5432:5432
    
    cassandra:
        build:
            context: resources/cassandra
            dockerfile: Dockerfile
        restart: always
        ports:
            - 9042:9042
